version: '3.8'

services:
  backend:
    container_name: ecom-backend-${ENVIRONMENT_NAME}
    build:
      context: .
      args:
        - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
        - BRANCH_NAME=${BRANCH_NAME}
      dockerfile: Docker/Dockerfile
    ports:
      - "${PORT}:3000"
    environment:
      - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
      - CHOKIDAR_USEPOLLING=true

networks:
  default:
    name: nginx-proxy
    external: true
