version: '3.8'

services:
  redis:
    container_name: primetime-backend-redis-${ENVIRONMENT_NAME}
    image: redis:alpine
    restart: on-failure
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_BIND=0.0.0.0
      - REDIS_MAXMEMORY=1gb
      - REDIS_LOGLEVEL=notice
    volumes:
      - ./data/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    env_file:
      - .env
    networks:
      - app

  db:
    image: mariadb:latest
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./data/database:/var/lib/mysql
    networks:
      - app

  app:
    container_name: primetime-backend-${ENVIRONMENT_NAME}
    build:
      context: .
      args:
        - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
        - BRANCH_NAME=${BRANCH_NAME}
      dockerfile: Docker/Dockerfile
    ports:
      - "3100:3001"
    environment:
      - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - redis
      - db
    networks:
      - app

  caddy:
    container_name: primetime-backend-caddy-${ENVIRONMENT_NAME}
    image: caddy
    restart: on-failure
    ports:
      - "${PORT}:80"
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - app
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy-data:/data
      - ./data/caddy-config/config
    networks:
      - app
      - nginx

networks:
  app:
    driver: bridge
    internal: true
  nginx:
    name: nginx-proxy
    external: true
