version: '3.8'

services:
  redis:
    container_name: primetime-backend-redis-${ENVIRONMENT_NAME}
    image: redis:alpine
    restart: on-failure
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_BIND=0.0.0.0
      - REDIS_MAXMEMORY=1gb
      - REDIS_LOGLEVEL=notice
    volumes:
      - ./redis_data:/data
    ports:
      - "${REDIS_PORT}:6379"
    env_file:
      - .env
    networks:
      - app

  app:
    container_name: primetime-backend-${ENVIRONMENT_NAME}
    build:
      context: .
      args:
        - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
        - BRANCH_NAME=${BRANCH_NAME}
      dockerfile: Docker/Dockerfile
    ports:
      - "${PORT}:3001"
    environment:
      - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app
      - nginx


networks:
  app:
    driver: bridge
    internal: true
  nginx:
    name: nginx-proxy
    external: true
